/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    animals: Animal;
    'animal-events': AnimalEvent;
    'adoption-requests': AdoptionRequest;
    tenants: Tenant;
    transactions: Transaction;
    volunteers: Volunteer;
    'document-templates': DocumentTemplate;
    'signed-documents': SignedDocument;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    animals: AnimalsSelect<false> | AnimalsSelect<true>;
    'animal-events': AnimalEventsSelect<false> | AnimalEventsSelect<true>;
    'adoption-requests': AdoptionRequestsSelect<false> | AdoptionRequestsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    volunteers: VolunteersSelect<false> | VolunteersSelect<true>;
    'document-templates': DocumentTemplatesSelect<false> | DocumentTemplatesSelect<true>;
    'signed-documents': SignedDocumentsSelect<false> | SignedDocumentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'Admin' | 'Financeiro' | 'Veterinário' | 'Voluntário' | 'Marketing';
  /**
   * Qual organização este usuário pertence (White Label).
   */
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Organizações parceiras e ONGs usando a plataforma (White Label).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Usado para resolver a interface da ONG correta baseado no subdomínio/domínio.
   */
  domain?: string | null;
  logo?: (number | null) | Media;
  /**
   * Cor principal em HEX (ex: #f97316)
   */
  primaryColor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animals".
 */
export interface Animal {
  id: number;
  nome: string;
  slug: string;
  especie: 'Cachorro' | 'Gato' | 'Outro';
  sexo: 'Macho' | 'Fêmea';
  porte: 'Pequeno' | 'Médio' | 'Grande';
  idade?: number | null;
  peso?: number | null;
  status: 'Resgatado' | 'Em tratamento' | 'Lar temporário' | 'Disponível' | 'Em adaptação' | 'Adotado' | 'Falecido';
  descricao?: string | null;
  historia?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  castrado?: boolean | null;
  vacinado?: boolean | null;
  vermifugado?: boolean | null;
  microchipado?: boolean | null;
  fotos?:
    | {
        foto?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  dataResgate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animal-events".
 */
export interface AnimalEvent {
  id: number;
  animal: number | Animal;
  tipo: string;
  descricao: string;
  data: string;
  imagens?:
    | {
        imagem?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  publico?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adoption-requests".
 */
export interface AdoptionRequest {
  id: number;
  animal: number | Animal;
  nome: string;
  telefone: string;
  cidade: string;
  endereco: string;
  tipoResidencia: 'Casa' | 'Apartamento' | 'Chácara/Sítio';
  possuiOutrosAnimais?: boolean | null;
  possuiTelaProtecao?: boolean | null;
  observacoes?: string | null;
  status: 'Interessado' | 'Entrevista' | 'Análise' | 'Aprovado' | 'Adaptação' | 'Adotado' | 'Reprovado';
  documentos?:
    | {
        documento?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Controle financeiro e doações
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  tipo: 'Receita' | 'Despesa' | 'Doação';
  valor: number;
  descricao: string;
  categoria?: string | null;
  data: string;
  comprovante?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cadastro de voluntários da ONG
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteers".
 */
export interface Volunteer {
  id: number;
  nome: string;
  contato: string;
  funcao: 'Resgate' | 'Lar Temporário' | 'Transporte' | 'Eventos' | 'Administrativo';
  disponibilidade?: string | null;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Modelos de documentos e termos (Adoção, Voluntariado, etc)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-templates".
 */
export interface DocumentTemplate {
  id: number;
  title: string;
  type: 'Adoção' | 'Voluntariado' | 'Outro';
  /**
   * Use placeholders como {nome_adotante}, {nome_animal}, {data_atual}.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro de termos assinados (Adoção, Responsabilidade, etc)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signed-documents".
 */
export interface SignedDocument {
  id: number;
  template: number | DocumentTemplate;
  adoptionRequest?: (number | null) | AdoptionRequest;
  volunteer?: (number | null) | Volunteer;
  signedAt: string;
  signatureIp?: string | null;
  status: 'Assinado' | 'Revogado';
  generatedPdf?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'animals';
        value: number | Animal;
      } | null)
    | ({
        relationTo: 'animal-events';
        value: number | AnimalEvent;
      } | null)
    | ({
        relationTo: 'adoption-requests';
        value: number | AdoptionRequest;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'volunteers';
        value: number | Volunteer;
      } | null)
    | ({
        relationTo: 'document-templates';
        value: number | DocumentTemplate;
      } | null)
    | ({
        relationTo: 'signed-documents';
        value: number | SignedDocument;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animals_select".
 */
export interface AnimalsSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  especie?: T;
  sexo?: T;
  porte?: T;
  idade?: T;
  peso?: T;
  status?: T;
  descricao?: T;
  historia?: T;
  castrado?: T;
  vacinado?: T;
  vermifugado?: T;
  microchipado?: T;
  fotos?:
    | T
    | {
        foto?: T;
        id?: T;
      };
  dataResgate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animal-events_select".
 */
export interface AnimalEventsSelect<T extends boolean = true> {
  animal?: T;
  tipo?: T;
  descricao?: T;
  data?: T;
  imagens?:
    | T
    | {
        imagem?: T;
        id?: T;
      };
  publico?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adoption-requests_select".
 */
export interface AdoptionRequestsSelect<T extends boolean = true> {
  animal?: T;
  nome?: T;
  telefone?: T;
  cidade?: T;
  endereco?: T;
  tipoResidencia?: T;
  possuiOutrosAnimais?: T;
  possuiTelaProtecao?: T;
  observacoes?: T;
  status?: T;
  documentos?:
    | T
    | {
        documento?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  logo?: T;
  primaryColor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  tipo?: T;
  valor?: T;
  descricao?: T;
  categoria?: T;
  data?: T;
  comprovante?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteers_select".
 */
export interface VolunteersSelect<T extends boolean = true> {
  nome?: T;
  contato?: T;
  funcao?: T;
  disponibilidade?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-templates_select".
 */
export interface DocumentTemplatesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  content?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signed-documents_select".
 */
export interface SignedDocumentsSelect<T extends boolean = true> {
  template?: T;
  adoptionRequest?: T;
  volunteer?: T;
  signedAt?: T;
  signatureIp?: T;
  status?: T;
  generatedPdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}