/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    animals: Animal;
    'animal-events': AnimalEvent;
    'adoption-requests': AdoptionRequest;
    tenants: Tenant;
    transactions: Transaction;
    volunteers: Volunteer;
    'document-templates': DocumentTemplate;
    'signed-documents': SignedDocument;
    'volunteer-invitations': VolunteerInvitation;
    'volunteer-files': VolunteerFile;
    'membership-term-versions': MembershipTermVersion;
    'volunteer-term-acceptances': VolunteerTermAcceptance;
    'audit-events': AuditEvent;
    pages: Page;
    posts: Post;
    categories: Category;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    animals: AnimalsSelect<false> | AnimalsSelect<true>;
    'animal-events': AnimalEventsSelect<false> | AnimalEventsSelect<true>;
    'adoption-requests': AdoptionRequestsSelect<false> | AdoptionRequestsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    volunteers: VolunteersSelect<false> | VolunteersSelect<true>;
    'document-templates': DocumentTemplatesSelect<false> | DocumentTemplatesSelect<true>;
    'signed-documents': SignedDocumentsSelect<false> | SignedDocumentsSelect<true>;
    'volunteer-invitations': VolunteerInvitationsSelect<false> | VolunteerInvitationsSelect<true>;
    'volunteer-files': VolunteerFilesSelect<false> | VolunteerFilesSelect<true>;
    'membership-term-versions': MembershipTermVersionsSelect<false> | MembershipTermVersionsSelect<true>;
    'volunteer-term-acceptances': VolunteerTermAcceptancesSelect<false> | VolunteerTermAcceptancesSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role:
    | 'Admin'
    | 'VOLUNTEER_MANAGER'
    | 'COMPLIANCE_OFFICER'
    | 'LEGAL_DIRECTOR'
    | 'Financeiro'
    | 'Veterinário'
    | 'Voluntário'
    | 'Marketing';
  /**
   * Qual organização este usuário pertence (White Label).
   */
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Organizações parceiras e ONGs usando a plataforma (White Label).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Usado para resolver a interface da ONG correta baseado no subdomínio/domínio.
   */
  domain?: string | null;
  logo?: (number | null) | Media;
  /**
   * Cor principal em HEX (ex: #f97316)
   */
  primaryColor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animals".
 */
export interface Animal {
  id: number;
  nome: string;
  slug: string;
  especie: 'Cachorro' | 'Gato' | 'Outro';
  sexo: 'Macho' | 'Fêmea';
  porte: 'Pequeno' | 'Médio' | 'Grande';
  idade?: number | null;
  peso?: number | null;
  status: 'Resgatado' | 'Em tratamento' | 'Lar temporário' | 'Disponível' | 'Em adaptação' | 'Adotado' | 'Falecido';
  descricao?: string | null;
  historia?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  castrado?: boolean | null;
  vacinado?: boolean | null;
  vermifugado?: boolean | null;
  microchipado?: boolean | null;
  fotos?:
    | {
        foto?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  cor?: string | null;
  doencas?: string | null;
  deficiencias?: string | null;
  dataResgate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animal-events".
 */
export interface AnimalEvent {
  id: number;
  animal: number | Animal;
  tipo: string;
  descricao: string;
  data: string;
  imagens?:
    | {
        imagem?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  publico?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adoption-requests".
 */
export interface AdoptionRequest {
  id: number;
  animal: number | Animal;
  nome: string;
  telefone: string;
  cidade: string;
  endereco: string;
  tipoResidencia: 'Casa' | 'Apartamento' | 'Chácara/Sítio';
  possuiOutrosAnimais?: boolean | null;
  possuiTelaProtecao?: boolean | null;
  observacoes?: string | null;
  status: 'Interessado' | 'Entrevista' | 'Análise' | 'Aprovado' | 'Adaptação' | 'Adotado' | 'Reprovado';
  documentos?:
    | {
        documento?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Controle financeiro e doações
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  /**
   * Vincule este gasto ou receita a um animal específico para controle de custo.
   */
  animal?: (number | null) | Animal;
  tipo: 'Receita' | 'Despesa' | 'Doação';
  valor: number;
  descricao: string;
  categoria?:
    | (
        | 'Ração'
        | 'Veterinário/Consulta'
        | 'Medicamentos'
        | 'Exames'
        | 'Transporte'
        | 'Banho/Tosa'
        | 'Evento/Rifa'
        | 'Apadrinhamento'
        | 'Infraestrutura'
        | 'Outros'
      )
    | null;
  data: string;
  /**
   * Desmarque caso este lançamento seja interno ou confidencial.
   */
  visivelNoSite?: boolean | null;
  comprovante?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cadastro de voluntários da ONG
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteers".
 */
export interface Volunteer {
  id: number;
  status: 'PENDING_REVIEW' | 'ACTIVE' | 'REJECTED' | 'RESIGNED' | 'SUSPENDED';
  nome: string;
  whatsapp: string;
  isLT?: boolean | null;
  capacidadeLT?: number | null;
  endereco?: string | null;
  cidade?: string | null;
  funcao: 'Resgate' | 'Lar Temporário' | 'Transporte' | 'Eventos' | 'Administrativo' | 'Marketing';
  disponibilidade?: string | null;
  ativo?: boolean | null;
  dataNascimento?: string | null;
  rg?: string | null;
  orgaoEmissor?: string | null;
  cpfEncrypted?: string | null;
  cpfBlindIndex?: string | null;
  cpfMasked?: string | null;
  email?: string | null;
  enderecoRua?: string | null;
  enderecoBairro?: string | null;
  cep?: string | null;
  areaAtuacao?: string | null;
  funcaoEspecifica?: string | null;
  dataIngresso?: string | null;
  horasMediasMes?: number | null;
  sourceInvitation?: (number | null) | VolunteerInvitation;
  submittedAt?: string | null;
  reviewedAt?: string | null;
  reviewedBy?: (number | null) | User;
  rejectionReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Links públicos para cadastro de voluntários
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-invitations".
 */
export interface VolunteerInvitation {
  id: number;
  tokenHash?: string | null;
  createdBy: number | User;
  expiresAt: string;
  maxUses: number;
  usedCount: number;
  status: 'ACTIVE' | 'EXPIRED' | 'EXHAUSTED' | 'REVOKED';
  lastUsedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Modelos de documentos e termos (Adoção, Voluntariado, etc)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-templates".
 */
export interface DocumentTemplate {
  id: number;
  title: string;
  type: 'Adoção' | 'Voluntariado' | 'Outro';
  /**
   * Use placeholders como {nome_adotante}, {nome_animal}, {data_atual}.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro de termos assinados (Adoção, Responsabilidade, etc)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signed-documents".
 */
export interface SignedDocument {
  id: number;
  template: number | DocumentTemplate;
  adoptionRequest?: (number | null) | AdoptionRequest;
  volunteer?: (number | null) | Volunteer;
  signedAt: string;
  signatureIp?: string | null;
  status: 'Assinado' | 'Revogado';
  generatedPdf?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-files".
 */
export interface VolunteerFile {
  id: number;
  volunteer?: (number | null) | Volunteer;
  invitation: number | VolunteerInvitation;
  submissionId: string;
  purpose: 'PERSONAL_PHOTO' | 'IDENTITY_DOCUMENT';
  storageProvider: 'R2';
  objectKey: string;
  mimeType: string;
  sizeBytes: number;
  sha256: string;
  uploadStatus: 'PENDING' | 'UPLOADED' | 'REJECTED' | 'DELETED';
  uploadedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-term-versions".
 */
export interface MembershipTermVersion {
  id: number;
  version: string;
  content: string;
  contentHash: string;
  documentKey?: string | null;
  effectiveFrom: string;
  effectiveUntil?: string | null;
  status: 'DRAFT' | 'PUBLISHED' | 'RETIRED';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-term-acceptances".
 */
export interface VolunteerTermAcceptance {
  id: number;
  volunteer: number | Volunteer;
  termVersion: number | MembershipTermVersion;
  acceptedAt: string;
  ipAddress: string;
  userAgent: string;
  contentHashAtAcceptance: string;
  statement: string;
  signedDocument?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  eventType: string;
  occurredAt: string;
  actorType: 'ADMIN' | 'PUBLIC_INVITATION' | 'SYSTEM';
  actorId?: string | null;
  actorRole?: string | null;
  targetType: string;
  targetId: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  legalGround?: string | null;
  targetNorm?: string | null;
  targetEntity?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Ex: sobre-nos, como-ajudar
   */
  slug: string;
  status: 'Rascunho' | 'Publicado';
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Identificador único na URL (ex: feira-de-adocao-sumare). Se vazio, será preenchido automaticamente a partir do título.
   */
  slug?: string | null;
  /**
   * Um resumo curto para aparecer no feed de notícias na página inicial e listagem.
   */
  excerpt?: string | null;
  category?: (number | null) | Category;
  coverImage?: (number | null) | Media;
  publishedAt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'animals';
        value: number | Animal;
      } | null)
    | ({
        relationTo: 'animal-events';
        value: number | AnimalEvent;
      } | null)
    | ({
        relationTo: 'adoption-requests';
        value: number | AdoptionRequest;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'volunteers';
        value: number | Volunteer;
      } | null)
    | ({
        relationTo: 'document-templates';
        value: number | DocumentTemplate;
      } | null)
    | ({
        relationTo: 'signed-documents';
        value: number | SignedDocument;
      } | null)
    | ({
        relationTo: 'volunteer-invitations';
        value: number | VolunteerInvitation;
      } | null)
    | ({
        relationTo: 'volunteer-files';
        value: number | VolunteerFile;
      } | null)
    | ({
        relationTo: 'membership-term-versions';
        value: number | MembershipTermVersion;
      } | null)
    | ({
        relationTo: 'volunteer-term-acceptances';
        value: number | VolunteerTermAcceptance;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animals_select".
 */
export interface AnimalsSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  especie?: T;
  sexo?: T;
  porte?: T;
  idade?: T;
  peso?: T;
  status?: T;
  descricao?: T;
  historia?: T;
  castrado?: T;
  vacinado?: T;
  vermifugado?: T;
  microchipado?: T;
  fotos?:
    | T
    | {
        foto?: T;
        id?: T;
      };
  cor?: T;
  doencas?: T;
  deficiencias?: T;
  dataResgate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animal-events_select".
 */
export interface AnimalEventsSelect<T extends boolean = true> {
  animal?: T;
  tipo?: T;
  descricao?: T;
  data?: T;
  imagens?:
    | T
    | {
        imagem?: T;
        id?: T;
      };
  publico?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adoption-requests_select".
 */
export interface AdoptionRequestsSelect<T extends boolean = true> {
  animal?: T;
  nome?: T;
  telefone?: T;
  cidade?: T;
  endereco?: T;
  tipoResidencia?: T;
  possuiOutrosAnimais?: T;
  possuiTelaProtecao?: T;
  observacoes?: T;
  status?: T;
  documentos?:
    | T
    | {
        documento?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  logo?: T;
  primaryColor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  animal?: T;
  tipo?: T;
  valor?: T;
  descricao?: T;
  categoria?: T;
  data?: T;
  visivelNoSite?: T;
  comprovante?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteers_select".
 */
export interface VolunteersSelect<T extends boolean = true> {
  status?: T;
  nome?: T;
  whatsapp?: T;
  isLT?: T;
  capacidadeLT?: T;
  endereco?: T;
  cidade?: T;
  funcao?: T;
  disponibilidade?: T;
  ativo?: T;
  dataNascimento?: T;
  rg?: T;
  orgaoEmissor?: T;
  cpfEncrypted?: T;
  cpfBlindIndex?: T;
  cpfMasked?: T;
  email?: T;
  enderecoRua?: T;
  enderecoBairro?: T;
  cep?: T;
  areaAtuacao?: T;
  funcaoEspecifica?: T;
  dataIngresso?: T;
  horasMediasMes?: T;
  sourceInvitation?: T;
  submittedAt?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  rejectionReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-templates_select".
 */
export interface DocumentTemplatesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  content?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signed-documents_select".
 */
export interface SignedDocumentsSelect<T extends boolean = true> {
  template?: T;
  adoptionRequest?: T;
  volunteer?: T;
  signedAt?: T;
  signatureIp?: T;
  status?: T;
  generatedPdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-invitations_select".
 */
export interface VolunteerInvitationsSelect<T extends boolean = true> {
  tokenHash?: T;
  createdBy?: T;
  expiresAt?: T;
  maxUses?: T;
  usedCount?: T;
  status?: T;
  lastUsedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-files_select".
 */
export interface VolunteerFilesSelect<T extends boolean = true> {
  volunteer?: T;
  invitation?: T;
  submissionId?: T;
  purpose?: T;
  storageProvider?: T;
  objectKey?: T;
  mimeType?: T;
  sizeBytes?: T;
  sha256?: T;
  uploadStatus?: T;
  uploadedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-term-versions_select".
 */
export interface MembershipTermVersionsSelect<T extends boolean = true> {
  version?: T;
  content?: T;
  contentHash?: T;
  documentKey?: T;
  effectiveFrom?: T;
  effectiveUntil?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-term-acceptances_select".
 */
export interface VolunteerTermAcceptancesSelect<T extends boolean = true> {
  volunteer?: T;
  termVersion?: T;
  acceptedAt?: T;
  ipAddress?: T;
  userAgent?: T;
  contentHashAtAcceptance?: T;
  statement?: T;
  signedDocument?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  eventType?: T;
  occurredAt?: T;
  actorType?: T;
  actorId?: T;
  actorRole?: T;
  targetType?: T;
  targetId?: T;
  ipAddress?: T;
  userAgent?: T;
  metadata?: T;
  legalGround?: T;
  targetNorm?: T;
  targetEntity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  coverImage?: T;
  publishedAt?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  copyright?: string | null;
  socialLinks?:
    | {
        platform: 'Instagram' | 'Facebook' | 'Twitter' | 'YouTube';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  copyright?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}