import type { CollectionConfig } from 'payload'

export const Volunteers: CollectionConfig = {
  slug: 'volunteers',
  labels: {
    singular: 'Voluntário',
    plural: 'Voluntários',
  },
  admin: {
    useAsTitle: 'nome',
    description: 'Cadastro de voluntários da ONG',
    group: 'Pessoas',
    components: { beforeList: ['/components/Admin/VolunteerInvitationActions'] },
  },
  access: {
    read: ({ req: { user } }) => Boolean(user?.role === 'Admin'),
    create: ({ req: { user } }) => Boolean(user?.role === 'Admin'),
    update: ({ req: { user } }) => Boolean(user?.role === 'Admin'),
    delete: ({ req: { user } }) => Boolean(user?.role === 'Admin'),
  },
  fields: [
    {
      name: 'status',
      type: 'select',
      label: 'Status do cadastro',
      options: ['PENDING_REVIEW', 'ACTIVE', 'REJECTED', 'RESIGNED', 'SUSPENDED'],
      defaultValue: 'ACTIVE',
      required: true,
    },
    {
      name: 'nome',
      type: 'text',
      required: true,
    },
    {
      name: 'whatsapp',
      type: 'text',
      label: 'WhatsApp',
      required: true,
    },
    {
      name: 'isLT',
      type: 'checkbox',
      label: 'Disponível para Lar Temporário (LT)?',
      defaultValue: false,
    },
    {
      name: 'capacidadeLT',
      type: 'number',
      label: 'Capacidade de Hospedagem (Animais)',
      admin: {
        condition: (data) => Boolean(data.isLT),
      },
    },
    {
      name: 'endereco',
      type: 'textarea',
      label: 'Endereço Completo',
    },
    {
      name: 'cidade',
      type: 'text',
      label: 'Cidade',
      defaultValue: 'Sumaré',
    },
    {
      name: 'funcao',
      type: 'select',
      label: 'Função Principal',
      options: ['Resgate', 'Lar Temporário', 'Transporte', 'Eventos', 'Administrativo', 'Marketing'],
      required: true,
    },
    {
      name: 'disponibilidade',
      type: 'text',
      label: 'Disponibilidade (Dias/Horários)',
    },
    {
      name: 'ativo',
      type: 'checkbox',
      label: 'Voluntário Ativo',
      defaultValue: true,
    },
    { name: 'dataNascimento', type: 'date', label: 'Data de nascimento', admin: { date: { pickerAppearance: 'dayOnly' } } },
    { name: 'rg', type: 'text', label: 'RG' },
    { name: 'orgaoEmissor', type: 'text', label: 'Órgão emissor' },
    { name: 'cpfEncrypted', type: 'text', admin: { hidden: true, readOnly: true } },
    { name: 'cpfBlindIndex', type: 'text', admin: { hidden: true, readOnly: true } },
    { name: 'cpfMasked', type: 'text', label: 'CPF', admin: { readOnly: true } },
    { name: 'email', type: 'email', label: 'E-mail' },
    { name: 'enderecoRua', type: 'text', label: 'Rua' },
    { name: 'enderecoBairro', type: 'text', label: 'Bairro' },
    { name: 'cep', type: 'text', label: 'CEP' },
    { name: 'areaAtuacao', type: 'text', label: 'Área de atuação' },
    { name: 'funcaoEspecifica', type: 'text', label: 'Função específica' },
    { name: 'dataIngresso', type: 'date', label: 'Data de ingresso' },
    { name: 'horasMediasMes', type: 'number', label: 'Horas médias por mês' },
    { name: 'sourceInvitation', type: 'relationship', relationTo: 'volunteer-invitations', admin: { readOnly: true } },
    { name: 'submittedAt', type: 'date', admin: { readOnly: true } },
    { name: 'reviewedAt', type: 'date', admin: { readOnly: true } },
    { name: 'reviewedBy', type: 'relationship', relationTo: 'users', admin: { readOnly: true } },
    { name: 'rejectionReason', type: 'textarea', admin: { readOnly: true } },
  ],
}
